AppKurs/Models/UserTask.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppKurs.Models
{
    public class UserTask
    {
        public int Id { get; set; }
        public string TaskTitle { get; set; }
        public string TaskText { get; set; }
        public string TaskTopic { get; set; }
        public string TaskAnswer { get; set; }
        public string TaskUser { get; set; }
        public int TaskRating { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ImageUrl { get; set; }

        [NotMapped]
        public virtual IFormFile ImageFile { get; set; }

        public string ImageStorageName { get; set; }

        public ICollection<SolvedTask> SolvedTasks { get; set; }
    }
}

AppKurs/Controllers/UserTaskController.cs
using AppKurs.CloudStorage;
using AppKurs.Data;
using AppKurs.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace AppKurs.Controllers
{
    public class UserTaskController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly ICloudStorage _cloudStorage;

        public UserTaskController(ApplicationDbContext db, ICloudStorage cloudStorage)
        {
            _db = db;
            _cloudStorage = cloudStorage;
        }

        private async Task UploadFile(UserTask userTask)
        {
            string fileNameForStorage = FormFileName(userTask.TaskTitle, userTask.ImageFile.FileName);
            userTask.ImageUrl = await _cloudStorage.UploadFileAsync(userTask.ImageFile, fileNameForStorage);
            userTask.ImageStorageName = fileNameForStorage;
        }

        private static string FormFileName(string title, string fileName)
        {
            var fileExtension = Path.GetExtension(fileName);
            var fileNameForStorage = $"{title}-{DateTime.Now.ToString("yyyyMMddHHmmss")}{fileExtension}";
            return fileNameForStorage;
        }

        public IActionResult Index() => View(_db.UserTasks.ToList());

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> CreateAsync([FromForm] UserTask model)
        {
            UserTask uTask = new UserTask
            {
                TaskTitle = model.TaskTitle,
                TaskText = model.TaskText,
                TaskAnswer = model.TaskAnswer,
                TaskUser = User.Identity.Name,
                TaskTopic = model.TaskTopic,
                ImageFile = model.ImageFile
            };
            
            if(uTask.ImageFile != null)
            {
                await UploadFile(uTask);
            }

            _db.UserTasks.Add(uTask);
            _db.SaveChanges();

            return Redirect("/Home/Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            var currentUser = await _db.ApplicationUsers
                .FirstOrDefaultAsync(m => m.UserName == User.Identity.Name);
            var usertask = await _db.UserTasks
                .FirstOrDefaultAsync(m => m.Id == id);

            if (currentUser == null)
            {
                return View(new SolvedViewModel { UserTasks = usertask });
            }

            SolvedTask sTask = new SolvedTask
            {
                TaskId = (int)id,
                UserId = currentUser.Id,
                Solved = false,
            };

            if (id == null)
            {
                return NotFound();
            }

            var currentTask = await _db.SolvedTasks
                .FirstOrDefaultAsync(t =>
                    t.UserId == currentUser.Id &&
                    t.TaskId == id);

            if (currentTask != null)
            {
                return View(new SolvedViewModel { UserTasks = usertask, SolvedTasks = currentTask });
            }
            else
            {
                _db.SolvedTasks.Add(sTask);
                _db.SaveChanges();
            }

            if (usertask == null)
            {
                return NotFound();
            }
            
            return View(new SolvedViewModel { UserTasks = usertask, SolvedTasks = sTask });
        }

        [HttpPost]
        public async Task<IActionResult> DetailsAsync(int? id, [FromForm] SolvedTask model)
        {
            var currentUser = await _db.ApplicationUsers
                .FirstOrDefaultAsync(m => m.UserName == User.Identity.Name);
            var currentTask = await _db.SolvedTasks
                .FirstOrDefaultAsync(t =>
                    t.UserId == currentUser.Id &&
                    t.TaskId == id);
            var thisAnswer = await _db.UserTasks
                .FirstOrDefaultAsync(t => t.Id == id);

            currentTask.UserAnswer = model.UserAnswer;
            _db.SolvedTasks.Update(currentTask);
            if(currentTask.UserAnswer == thisAnswer.TaskAnswer) currentTask.Solved = true;
            _db.SaveChanges();

            return RedirectToAction("Details");
        }

        [HttpPost, Route("UserTask/DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userTask = await _db.UserTasks.FindAsync(id);

            if(userTask.ImageStorageName != null)
            {
                await _cloudStorage.DeleteFileAsync(userTask.ImageStorageName);
            }

            _db.UserTasks.Remove(userTask);
            await _db.SaveChangesAsync();
            return Redirect("/Home/Index");
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var userTask = await _db.UserTasks.FindAsync(id);
            if(userTask == null)
            {
                return NotFound();
            }
            return View(userTask);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit (int id, [Bind("Id,TaskTitle,TaskTopic,TaskText,ImageUrl,ImageFile,ImageStorageName")] UserTask userTask)
        {
            if(id != userTask.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(userTask.ImageFile != null)
                    {
                        if(userTask.ImageStorageName != null)
                        {
                            await _cloudStorage.DeleteFileAsync(userTask.ImageStorageName);
                        }

                        await UploadFile(userTask);
                    }

                    userTask.TaskUser = userTask.TaskUser;
                    _db.Update(userTask);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserTaskExists(userTask.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userTask);
        }

        private bool UserTaskExists(int id)
        {
            return _db.UserTasks.Any(e => e.Id == id);
        }
    }
}

AppKurs/Views/UserTask/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model UserTask
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = "Create Task";
}

<div class="col-md-7">
    <form method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label>@Localizer["Title"]</label>
            <input class="form-control" asp-for="TaskTitle" />
        </div>
        <div class="form-group">
            <label>@Localizer["Subject"]</label>
            <select class="form-control" asp-for="TaskTopic" aria-label="Default select example">
                <option selected>@Localizer["Algebra"]</option>
                <option value="Geometry">@Localizer["Geometry"]</option>
                <option value="Programming">@Localizer["Programming"]</option>
            </select>
        </div>
        <div class="form-group">
            <label>@Localizer["Text"]</label>
            <textarea type="text" class="form-control" asp-for="TaskText"></textarea>
        </div>
        <div class="form-group">
            <label>@Localizer["Image File"]</label>
            <input asp-for="ImageFile" type="file" class="form-control" />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>@Localizer["Answer"]</label>
            <input class="form-control" asp-for="TaskAnswer" />
        </div>
        <button type="submit" class="btn btn-primary">@Localizer["Create"]</button>
    </form>
</div>

AppKurs/Views/UserTask/Details.cshtml
@using AppKurs.Models
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model SolvedViewModel
@{
    ViewData["Title"] = @Model.UserTasks.TaskTitle;
}


<div class="col-md text-center">
    <h1 class="">@Model.UserTasks.TaskTitle</h1>
</div>
<div class="col-md">
    <h3>@Model.UserTasks.TaskTopic</h3>
    <p class="lead">@Model.UserTasks.TaskText</p>
</div>
@if (Model.UserTasks.ImageUrl != null)
{
    <img src="@Url.Content(Model.UserTasks.ImageUrl)" class="img-fluid" alt="Image" />
}

@if (User.Identity.IsAuthenticated && !(Model.SolvedTasks.Solved))
{
    <form method="post" class="col-md-6 mt-3">
        <div class="mb-3">
            <label for="answer" class="form-label">@Localizer["Your answer"]</label>
            <input name="UserAnswer" type="text" class="form-control" id="answer">
        </div>
        <button type="submit" class="btn btn-primary">
            @Localizer["Answer"]
        </button>
    </form>
    @if (Model.SolvedTasks.UserAnswer != null)
    {
        <div class="col-md card bg-danger mt-3">
            <h2 class="text-light text-center">@Localizer["Wrong Answer"]</h2>
        </div>
    }
}

@if (User.Identity.Name == Model.UserTasks.TaskUser || User.IsInRole("admin"))
{
    <a class="btn btn-success mt-3" asp-action="Edit" asp-route-id="@Model.UserTasks.Id">@Localizer["Edit"]</a>
    <form asp-controller="UserTask" asp-action="DeleteConfirmed" asp-route-id="@Model.UserTasks.Id" method="post" class="col-md-6 mt-3">
        <button type="submit" class="btn btn-danger">@Localizer["Delete"]</button>
    </form>
}

@if (User.Identity.IsAuthenticated && Model.SolvedTasks.Solved)
{
    <div class="col-md card bg-success mt-3">
        <h2 class="text-light text-center">@Localizer["Task Solved"]</h2>
    </div>
}
<div class="col-md mt-3">
    @Localizer["Author"]: <a asp-controller="Home" asp-action="UserPage" asp-route-username="@Model.UserTasks.TaskUser"><b>@Model.UserTasks.TaskUser</b></a>
</div>

AppKurs/Views/UserTask/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@model AppKurs.Models.UserTask

@{
    ViewData["Title"] = @Localizer["Edit"];
}

<div class="row">
    <div class="col-md-7">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label>@Localizer["Title"]</label>
                <input asp-for="TaskTitle" class="form-control" />
                <span asp-validation-for="TaskTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@Localizer["Subject"]</label>
                <select class="form-control" asp-for="TaskTopic" aria-label="Default select example">
                    <option selected>@Localizer["Algebra"]</option>
                    <option value="Geometry">@Localizer["Geometry"]</option>
                    <option value="Programming">@Localizer["Programming"]</option>
                </select>
                <span asp-validation-for="TaskTopic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@Localizer["Text"]</label>
                <textarea asp-for="TaskText" class="form-control"></textarea>
                <span asp-validation-for="TaskText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>@Localizer["Answer"]</label>
                <input class="form-control" asp-for="TaskAnswer" />
            </div>
            <div class="form-group">
                <input asp-for="ImageUrl" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label>@Localizer["Image"]</label>
                <input asp-for="ImageFile" type="file" class="form-control">
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="ImageStorageName" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>